### ISSUE TITLE
Failed to find source of module Product in any of the following ...

### ISSUE THREAD

**Issue by patrikja** [DSLsofMath/FLABloM#1]
Forgotten git add?
$ agda -i ~/lib/agda-stdlib/ -i . test.agda 
Failed to find source of module Product in any of the following
locations:
  /home/patrikj/src/DSLM/FLABloM/Product.agda
  /home/patrikj/src/DSLM/FLABloM/Product.lagda
  /home/patrikj/lib/agda-stdlib/Product.agda
  /home/patrikj/lib/agda-stdlib/Product.lagda
  /home/patrikj/.cabal/share/x86_64-linux-ghc-7.10.1/Agda-2.4.2.3/lib/prim/Product.agda
  /home/patrikj/.cabal/share/x86_64-linux-ghc-7.10.1/Agda-2.4.2.3/lib/prim/Product.lagda
when scope checking the declaration
  open import Product

**Comment by adamse** [comment]
Whoops. Added the file.

**Comment by adamse** [comment]
d5f32627c457799a90587ad39130eab06d003817
